
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ID ID_LING LB VALdic : EsEs : Es LB E Es : EE : ITENSE : ITENS : ITEM ITENSITENS : ITEMITEM : AT_CONCITEM : LINGAT_CONC : ID ":" VAL "\\n"LING : ID_LING ":" "\\n" TsTs : T TsTs : TT : "-" VAL AT_TsAT_Ts : "\\n" AT_T AT_TsAT_Ts : "\\n"AT_T : "+" ID ":" VAL'
    
_lr_action_items = {'LB':([0,2,3,4,5,6,7,10,11,14,17,18,19,21,23,24,27,],[-5,10,-3,-4,-7,-8,-9,-5,-6,-2,-10,-11,-13,-12,-14,-16,-15,]),'$end':([0,1,2,3,4,5,6,7,10,11,14,17,18,19,21,23,24,27,],[-5,0,-1,-3,-4,-7,-8,-9,-5,-6,-2,-10,-11,-13,-12,-14,-16,-15,]),'ID':([0,5,6,7,10,17,18,19,21,23,24,26,27,],[8,8,-8,-9,8,-10,-11,-13,-12,-14,-16,28,-15,]),'ID_LING':([0,5,6,7,10,17,18,19,21,23,24,27,],[9,9,-8,-9,9,-10,-11,-13,-12,-14,-16,-15,]),':':([8,9,28,],[12,13,29,]),'VAL':([12,20,29,],[15,22,30,]),'\n':([13,15,22,25,30,],[16,17,24,24,-17,]),'-':([16,19,23,24,27,],[20,20,-14,-16,-15,]),'+':([24,],[26,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'dic':([0,],[1,]),'Es':([0,],[2,]),'E':([0,10,],[3,14,]),'ITENS':([0,5,10,],[4,11,4,]),'ITEM':([0,5,10,],[5,5,5,]),'AT_CONC':([0,5,10,],[6,6,6,]),'LING':([0,5,10,],[7,7,7,]),'Ts':([16,19,],[18,21,]),'T':([16,19,],[19,19,]),'AT_Ts':([22,25,],[23,27,]),'AT_T':([24,],[25,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> dic","S'",1,None,None,None),
  ('dic -> Es','dic',1,'p_1','dicmed_sem.py',5),
  ('Es -> Es LB E','Es',3,'p_2','dicmed_sem.py',9),
  ('Es -> E','Es',1,'p_3','dicmed_sem.py',12),
  ('E -> ITENS','E',1,'p_4','dicmed_sem.py',15),
  ('E -> <empty>','E',0,'p_5','dicmed_sem.py',18),
  ('ITENS -> ITEM ITENS','ITENS',2,'p_6','dicmed_sem.py',21),
  ('ITENS -> ITEM','ITENS',1,'p_7','dicmed_sem.py',24),
  ('ITEM -> AT_CONC','ITEM',1,'p_8','dicmed_sem.py',27),
  ('ITEM -> LING','ITEM',1,'p_9','dicmed_sem.py',30),
  ('AT_CONC -> ID : VAL \n','AT_CONC',4,'p_10','dicmed_sem.py',33),
  ('LING -> ID_LING : \n Ts','LING',4,'p_11','dicmed_sem.py',36),
  ('Ts -> T Ts','Ts',2,'p_12','dicmed_sem.py',39),
  ('Ts -> T','Ts',1,'p_13','dicmed_sem.py',42),
  ('T -> - VAL AT_Ts','T',3,'p_14','dicmed_sem.py',45),
  ('AT_Ts -> \n AT_T AT_Ts','AT_Ts',3,'p_15','dicmed_sem.py',48),
  ('AT_Ts -> \n','AT_Ts',1,'p_16','dicmed_sem.py',51),
  ('AT_T -> + ID : VAL','AT_T',4,'p_17','dicmed_sem.py',54),
]
