
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ID ID_LING LB VALdic : EsEs : E LB EsEs : EE : ITENSE : ITENS : ITEM "\\n" ITENSITENS : ITEMITEM : AT_CONCITEM : LINGAT_CONC : ID ":" VALLING : ID_LING ":" "\\n" TsTs : T "\\n" TsTs : TT : "-" VAL AT_TsAT_Ts : AT_Ts AT_TAT_Ts : AT_T : "\\n" "+" ID ":" VAL'
    
_lr_action_items = {'LB':([0,3,4,5,6,7,10,15,16,18,19,22,23,24,25,30,],[-5,10,-4,-7,-8,-9,-5,-6,-10,-11,-13,-16,-12,-14,-15,-17,]),'$end':([0,1,2,3,4,5,6,7,10,14,15,16,18,19,22,23,24,25,30,],[-5,0,-1,-3,-4,-7,-8,-9,-5,-2,-6,-10,-11,-13,-16,-12,-14,-15,-17,]),'ID':([0,10,11,27,],[8,8,8,28,]),'ID_LING':([0,10,11,],[9,9,9,]),'\n':([5,6,7,13,16,18,19,22,23,24,25,30,],[11,-8,-9,17,-10,-11,21,-16,-12,26,-15,-17,]),':':([8,9,28,],[12,13,29,]),'VAL':([12,20,29,],[16,22,30,]),'-':([17,21,],[20,20,]),'+':([26,],[27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'dic':([0,],[1,]),'Es':([0,10,],[2,14,]),'E':([0,10,],[3,3,]),'ITENS':([0,10,11,],[4,4,15,]),'ITEM':([0,10,11,],[5,5,5,]),'AT_CONC':([0,10,11,],[6,6,6,]),'LING':([0,10,11,],[7,7,7,]),'Ts':([17,21,],[18,23,]),'T':([17,21,],[19,19,]),'AT_Ts':([22,],[24,]),'AT_T':([24,],[25,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> dic","S'",1,None,None,None),
  ('dic -> Es','dic',1,'p_1','dicmed_sem.py',5),
  ('Es -> E LB Es','Es',3,'p_2','dicmed_sem.py',9),
  ('Es -> E','Es',1,'p_3','dicmed_sem.py',12),
  ('E -> ITENS','E',1,'p_4','dicmed_sem.py',15),
  ('E -> <empty>','E',0,'p_5','dicmed_sem.py',18),
  ('ITENS -> ITEM \n ITENS','ITENS',3,'p_6','dicmed_sem.py',21),
  ('ITENS -> ITEM','ITENS',1,'p_7','dicmed_sem.py',24),
  ('ITEM -> AT_CONC','ITEM',1,'p_8','dicmed_sem.py',27),
  ('ITEM -> LING','ITEM',1,'p_9','dicmed_sem.py',30),
  ('AT_CONC -> ID : VAL','AT_CONC',3,'p_10','dicmed_sem.py',33),
  ('LING -> ID_LING : \n Ts','LING',4,'p_11','dicmed_sem.py',36),
  ('Ts -> T \n Ts','Ts',3,'p_12','dicmed_sem.py',39),
  ('Ts -> T','Ts',1,'p_13','dicmed_sem.py',42),
  ('T -> - VAL AT_Ts','T',3,'p_14','dicmed_sem.py',45),
  ('AT_Ts -> AT_Ts AT_T','AT_Ts',2,'p_15','dicmed_sem.py',48),
  ('AT_Ts -> <empty>','AT_Ts',0,'p_16','dicmed_sem.py',51),
  ('AT_T -> \n + ID : VAL','AT_T',5,'p_17','dicmed_sem.py',54),
]
